### ISSUE TITLE
Fall back to sendMessage if a daily announcement's caption is too long

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#76]
This past Wednesday's 8 a.m. Pacific announcement failed:

```
2019-09-04 08:00:14,958 ERROR loop.py:72] Ignoring uncaught error while dispatching:
Traceback (most recent call last):
  File "lib/python3.6/site-packages/ntelebot/loop.py", line 70, in run
    callback()
  File "lib/python3.6/site-packages/metabot/modules/events.py", line 42, in _hourly
    _daily_messages(multibot, records)
  File "lib/python3.6/site-packages/metabot/modules/events.py", line 76, in _daily_messages
    disable_notification=True)
  File "lib/python3.6/site-packages/ntelebot/bot.py", line 68, in __call__
    raise ntelebot.errors.Error(data)
ntelebot.errors.Error: {'ok': False, 'error_code': 400, 'description': 'Bad Request: MEDIA_CAPTION_TOO_LONG'}
```

From #74:

> For images, the announcement could be changed from a [sendMessage](https://core.telegram.org/bots/api#sendmessage) to a [sendPhoto](https://core.telegram.org/bots/api#sendphoto), though the text of the message will become a "caption" instead—and will be limited to 1024 characters.

1. We could do something like pass the caption text through [`metabot.util.html.sanitize`](https://github.com/nmlorg/metabot/blob/67148e0024c2d54bb4e468a4e0647ffccd6760a9/metabot/util/html.py#L76), and revert to `sendMessage` if its length is greater than 1024.
2. Alternatively we could capture that error and retry using `sendMessage`.

---

While working on this, we should also just improve error handling in the daily announcement loop so one announcement's failure won't cause all announcements for that time slot to be skipped (see 26c7734).

**Comment by nmlorg** [comment]
> While working on this, we should also just improve error handling in the daily announcement loop so one announcement's failure won't cause all announcements for that time slot to be skipped (see [26c7734](https://github.com/nmlorg/metabot/commit/26c77343e0219226e565e51678908273d343bd97)).

This was done in 358ce89.
